---
- hosts: jenkins-server
  become: true 

  tasks: 
  - name: add jenkins key 
    ansible.builtin.rpm_key:
      key:  https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      state: present 

  - name: add jenkins repo 
    ansible.builtin.yum_repository:
      name: jenkins
      description: Jenkins Repository
      baseurl: https://pkg.jenkins.io/redhat-stable/
      state: present 

  - name: install java
    ansible.builtin.yum: 
      update_cache: yes
      name: 
        - java-17-amazon-corretto
        - jenkins
        - git
        - maven
      state: present

  - name: install jenkins
    ansible.builtin.yum: 
      update_cache: yes
      name: jenkins 
      state: present 

  - name: start jenkins service 
    ansible.builtin.service: 
      name: jenkins 
      state: started 

  - name: enable jenkins to start at boot time 
    ansible.builtin.service: 
      name: jenkins 
      enabled: yes 

  - name: set hostname
    ansible.builtin.hostname:
      name: jenkins-server

  # jenkins requires at least 1G
  - name: resize tmpfs
    ansible.builtin.shell: mount -o remount,size=2g /tmp/
