---
- hosts: [ nginx, tomcat ]
  become: yes
  gather_facts: yes

  tasks:
  - name: Install Packages on Ubuntu
    ansible.builtin.apt:
      update_cache: yes
      pkg: "{{ packages }}"
      state: present
    when:
      ansible_distribution == 'Ubuntu'

  - name: Install Packages on Amazon Linux
    ansible.builtin.yum:
      update_cache: yes
      pkg: "{{ packages }}"
      state: present
    when:
      ansible_distribution == 'Amazon'
