---
- hosts: [ nginx, tomcat ]
  become: yes
  gather_facts: yes

  tasks:
  - name: Install Packages on Ubuntu
    ansible.builtin.apt:
      pkg: "{{ packages }}"
      state: present
    when:
      inventory_hostname == 'nginx'

  - name: Install Packages on Amazon Linux
    ansible.builtin.yum:
      pkg: "{{ packages }}"
      state: present
    when:
      inventory_hostname == 'tomcat'
